pages:
  image: node:latest
  stage: deploy
  script:
    - npm run build
    - mv public public.old
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

  before_script:
    - npm install
